### ISSUE TITLE
Bowser fails to open html files 

### ISSUE THREAD

**Issue by Greggk** [bitwiseworks/otter-browser-os2#1]
**Describe the bug**
Select File->Open then navigate to find an HTML file select it and you get an error file not found. It appears it is trying to use UNIX style paths instead of os2 style paths.

**Comment by dmik** [comment]
This is not an Otter problem, it is a Chromium or its Qt wrapper layer problem, see https://github.com/bitwiseworks/qtwebengine-os2/issues/7. Closing this in favour of that one.
