### ISSUE TITLE
Delete key doesn't work

### ISSUE THREAD

**Issue by Greggk** [bitwiseworks/otter-browser-os2#3]
In filling out these tickets I have tried using the delete key to correct typing errors nothing happens. I have to reposition the curser and use the backspace key to delete the character.

**Comment by dmik** [comment]
I can confirm that — it only relates to web content (input fields on web pages) though. Qt input (e.g. address bar) works as expected. And given that I can also see it in the simplebrowser example, it must be either a Chromium or a QtWebEngine wrapper problem. I suspect the latter, will create a ticket there.
